# Generated by Django 2.2.1 on 2019-09-30 13:16

from django.db import migrations, models
import django.db.models.deletion
import django_forcedfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_tag', models.TextField()),
                ('description', models.CharField(max_length=300)),
                ('created_at', django_forcedfields.TimestampField(auto_now_add=True)),
                ('updated_at', django_forcedfields.TimestampField(auto_now=True)),
                ('image', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileusers.mobileuser')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
