# Generated by Django 2.2.1 on 2019-08-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaints',
            new_name='complaint',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaint',
        ),
    ]
