# Generated by Django 2.2.1 on 2019-11-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
    ]
