# Generated by Django 2.2.1 on 2019-09-30 13:00

from django.db import migrations, models
import django_forcedfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobileuser',
            fields=[
                ('google_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('nickname', models.CharField(max_length=300)),
                ('phoneNo', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=300, null=True)),
                ('nic', models.CharField(max_length=12, null=True, unique=True)),
                ('created_at', django_forcedfields.TimestampField(auto_now_add=True)),
                ('updated_at', django_forcedfields.TimestampField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
