# Generated by Django 2.2.1 on 2019-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobileusers',
            fields=[
                ('nic', models.CharField(max_length=12, null=True)),
                ('nickname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
