# Generated by Django 2.2.1 on 2019-08-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mobileusers',
            new_name='mobileuser',
        ),
    ]
