# Generated by Django 2.2.1 on 2019-09-30 13:18

from django.db import migrations, models
import django_forcedfields
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=4000)),
                ('expected_answer', django_mysql.models.JSONField(default=dict)),
                ('created_at', django_forcedfields.TimestampField(auto_now_add=True)),
                ('updated_at', django_forcedfields.TimestampField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
