# Generated by Django 2.2.1 on 2019-09-09 07:38

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected_answer',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
