# Generated by Django 2.2.1 on 2019-09-30 13:12

from django.db import migrations, models
import django.db.models.deletion
import django_forcedfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('mobileusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa', models.TextField()),
                ('device_signature', models.TextField()),
                ('created_at', django_forcedfields.TimestampField(auto_now_add=True)),
                ('updated_at', django_forcedfields.TimestampField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileusers.mobileuser')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
