# Generated by Django 2.2.1 on 2019-09-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('reviews', '0003_auto_20190909_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
