# Generated by Django 2.2.1 on 2019-09-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
