# Generated by Django 2.2.1 on 2019-09-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190910_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='geo_tag',
        ),
    ]
