# Generated by Django 2.2.1 on 2019-09-30 13:10

from django.db import migrations, models
import django_forcedfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=1000)),
                ('geo_tag', models.TextField()),
                ('address', models.CharField(max_length=3000)),
                ('created_at', django_forcedfields.TimestampField(auto_now_add=True)),
                ('updated_at', django_forcedfields.TimestampField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
    ]
