# Generated by Django 2.2.1 on 2019-10-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='slug',
        ),
    ]
